ignoredBuiltDependencies:
  - '@parcel/watcher'
  - '@prisma/client'
  - '@prisma/engines'
  - '@tailwindcss/oxide'
  - esbuild
  - prisma
  - unrs-resolver
  - vue-demi

onlyBuiltDependencies:
  - better-sqlite3
  - sharp
